# Generated by Django 4.1.7 on 2023-03-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typerek', '0004_rename_p_diff_goals_bets_p_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bets',
            name='p_away_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bets',
            name='p_extra_bet',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bets',
            name='p_home_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bets',
            name='p_joker',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bets',
            name='p_result',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bets',
            name='p_sum_goals',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bets',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
