# Generated by Django 4.1.7 on 2023-03-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typerek', '0006_alter_matches_extra_bet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='extra_bet_name',
            field=models.CharField(blank=True, default='Wpisz zaklad lub pozostaw puste', max_length=100, null=True),
        ),
    ]
