# Generated by Django 4.1.7 on 2023-04-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typerek', '0008_alter_bets_extra_bet_alter_bets_joker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bets',
            name='joker',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
