# Generated by Django 4.1.7 on 2023-04-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typerek', '0009_alter_bets_joker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bets',
            name='joker',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
