# Generated by Django 4.1.7 on 2023-06-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typerek', '0011_remove_bets_multiplier_alter_matches_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bets',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
