# Generated by Django 4.1.7 on 2023-06-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typerek', '0012_alter_bets_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
