# Generated by Django 4.1.7 on 2023-09-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typerek', '0013_matches_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='extra_bet_name',
            field=models.CharField(blank=True, default='Ż. kartki w meczu', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='multiplier',
            field=models.IntegerField(default=1),
        ),
    ]
