# Generated by Django 4.1.7 on 2023-09-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typerek', '0014_alter_matches_extra_bet_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
