# Generated by Django 4.1.7 on 2023-12-26 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typerek', '0015_alter_matches_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('question', models.CharField(max_length=30)),
                ('answer', models.CharField(max_length=100)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typerek.league')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=30)),
                ('p_answer', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typerek.questions')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
