# Generated by Django 4.1.7 on 2023-12-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typerek', '0016_questions_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='choice_list',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
