# Generated by Django 4.1.7 on 2025-06-26 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typerek', '0017_questions_choice_list_alter_questions_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='bets',
            name='status',
            field=models.IntegerField(blank=True, default=0, help_text='0 - user wszedl w mecz,ale nie obstawił, 1 - user obstawił, 2 - skrypt przyliczył punkty', null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='status',
            field=models.PositiveIntegerField(default=0, help_text='0 - Nieaktywna, 1 - Aktywna (pokaż userowi)'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='status',
            field=models.IntegerField(blank=True, default=0, help_text='0 - Otwarty, 1 - Zakończony (uwzg. przy przel.)', null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='status',
            field=models.IntegerField(blank=True, default=0, help_text='0 - Otwarty, 1 - Zakończony (uwzg. przy przel.)', null=True),
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1000)),
                ('status', models.IntegerField(blank=True, default=1, help_text='0 - nieaktywny, 1 - aktywny', null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typerek.categoryarticles')),
            ],
        ),
    ]
