# Generated by Django 4.1.7 on 2025-06-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typerek', '0018_categoryarticles_alter_bets_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
