# Generated by Django 4.1.7 on 2025-06-27 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typerek', '0019_alter_articles_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, help_text='Maksymalny rozmiar: 200KB. Dozwolone formaty: jpg, jpeg, png, gif.', null=True, upload_to='image_articles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
