# Generated by Django 4.1.7 on 2025-07-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typerek', '0020_articles_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_rules', models.TextField(null=True)),
                ('payment', models.TextField(null=True)),
                ('additional_info', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.TextField(),
        ),
    ]
