# Generated by Django 4.1.7 on 2025-07-17 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typerek', '0022_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='telefon',
            new_name='phone',
        ),
    ]
