# Generated by Django 4.1.7 on 2025-07-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typerek', '0023_rename_telefon_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='choice_list',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
