# Generated by Django 4.1.7 on 2025-08-02 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typerek', '0024_alter_questions_choice_list_alter_questions_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favourite_club',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, help_text='Maksymalny rozmiar: 200KB. Dozwolone formaty: jpg, jpeg, png, gif.', null=True, upload_to='image_users/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='short_info',
            field=models.CharField(help_text='max 100 znaków', max_length=100, null=True),
        ),
    ]
