# Generated by Django 4.1.7 on 2025-08-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typerek', '0025_remove_userprofile_phone_userprofile_birth_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favourite_club',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='short_info',
            field=models.CharField(blank=True, help_text='max 100 znaków', max_length=100, null=True),
        ),
    ]
