# Generated by Django 4.1.7 on 2025-08-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typerek', '0026_alter_userprofile_favourite_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bet_tactic',
            field=models.CharField(blank=True, help_text='max 100 znaków', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='status',
            field=models.PositiveIntegerField(default=0, help_text='0 - Nieaktywna, 1 - Aktywna (pokaż userowi), 2 - Archiwalna (pokaż userowi)'),
        ),
    ]
