# Generated by Django 4.1.7 on 2025-09-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typerek', '0027_userprofile_bet_tactic_alter_league_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bets',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
