# Generated by Django 4.1.7 on 2025-11-19 22:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('typerek', '0028_answers_last_updated_bets_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
